### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by wailinkyaww** [HlaingTinHtun/Data-Structure-Algorithm-In-Burmese#1]
မြန်မာလို ရေးထားတဲ့ articles တွေနဲ့ content တွေမှာဗျာ၊ font-size ကတော့ အဆင်ပြေတယ်။ ဒါပေမဲ့ line-spacing က နည်းနည်း အနှောင့်အယှက် ပေးနေသလို မြင်တယ်ဗျ။ `line-height` နည်းနည်း ထပ်များပေးရင် audience အတွက် ဖတ်ရတာ ပိုပြီး အဆင်ပြေမယ်လို့ထင်တယ်။

**Comment by HlaingTinHtun** [comment]
@wailinkyaww Thanks for the contribution & suggestion. I will update the document.

**Comment by HlaingTinHtun** [comment]
added paragraph line height in minor update (**v2.1**).
